name: mymanislier
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.2
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.1
  injectable: ^2.5.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3
  path_provider: ^2.1.4
  crypto: ^3.0.6
  collection: ^1.18.0
  gap: ^3.0.1
  flutter_svg: ^2.0.16
  flutter_easyloading: ^3.0.5
  pinput: ^5.0.0
  animated_text_kit: ^4.2.2
  flutter_ripple:
  siri_wave:
  flutter_sinusoidals_v2: ^0.2.3
  image_picker: ^1.1.2
  readmore: ^3.0.0
  syncfusion_flutter_charts: ^28.1.37

  cupertino_icons: ^1.0.8

flutter_gen:
  line_lenght: 160
  null_safety: true
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
  output: lib/app/utils/helpers/generated 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.4
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  intl_utils: ^2.8.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/png/
    - assets/images/icon/
    - assets/images/png/home/
    - assets/images/png/other/
    - assets/images/png/authentication/
    - assets/images/svg/splash/
    - assets/images/svg/authentication/
    - assets/images/svg/home/
    - assets/images/svg/other/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
        - asset: assets/fonts/nunito/Nunito-Light.ttf
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-Black.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf

        
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf


flutter_native_splash:
  color: "#FFFFFF"
  android: true 
  ios: true     


  
